services:
  preintern-nginx:
    container_name: "preintern-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - preintern-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  preintern-app:
    container_name: "preintern-app"
    build:
      context: ./docker/php
    depends_on:
      - preintern-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  preintern-mysql:
    image: mysql
    command: --max_allowed_packet=32505856
    container_name: "preintern-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CFMpreintern
    ports:
      - 3306:3306
